### PR TITLE
Sync from NCAR/main + Thompson params

### LINKED ISSUE #320: Non-warning log writes occurring when Land IAU is used
# Description

In some recent runs of the new GDAS configuration, it was noted that the stdout file had many extra writes to the log that were not necessary. The log in this instance went from ~20k lines to ~2 million. The line was removed from the NoahMP repo (https://github.com/NOAA-EMC/noahmp/commit/393687ef2b0139370a76320ffee3cc949e797c5e) but I would want to do the same in this repo.

## Steps to Reproduce
Run a case with Land IAU and look at the stdout file.

### PR DESCRIPTION
**Pull request by grantfirl**
## Description of Changes:
Changes from: 
1. https://github.com/NCAR/ccpp-physics/pull/1159

The issue: Some subroutines do not have return statements after an error occurs. Instead two variables errflg and errmsg are reset or re-initialized in subsequent calls, and if an error occurs it is not captured and the program continues without stopping. Please note that some calls already have if(errflg/=0) return in place.

This PR fixes an issue to return right after an error occurs. Subroutines that use errflg and errmsg should be checked for errflg and abort if necessary. Insert if(errflg/=0) return after such calls.

In addition the following is added:

Remove unnecessary return statements at the end of subroutines. In one case, there were actually two return statements right after each other.
Improve error messages and remove duplicate print statements if they are the same as the errmsg.
Change “can not” to “cannot” and other minor additions.
UPDATE: Thanks to reviewers' feedback, this PR also includes cleanup of GFS_phys_time_vary.fv3.F90 to remove copy_error calls from one-thread region (accessing errmsg and errflg directly).

https://github.com/NCAR/ccpp-physics/pull/1152 description (issue):
The way w3emc is used in GFS_time_vary_pre is not safe, since there is no protection against argument mismatches in case the wrong version of the library (e.g., _4 instead of _d) is used. This came up during the debugging of a w3emc build issue with Intel oneAPI ifx.

A detailed description can be found here: https://github.com/JCSDA/spack-stack/issues/1716

The issue also provides a code snippet that protects against using a wrong kind for the integer and real arguments in the w3difdat routines.

2. reviewer changes from https://github.com/NCAR/ccpp-physics/pull/1154 (parameterized types in canopy_utils_mod)

3. reviewer changes from https://github.com/NCAR/ccpp-physics/pull/1153 (remove dependence on MPI in mp_tempo_post, other minor naming changes)

4. bugfix for NSSL MP: https://github.com/NCAR/ccpp-physics/pull/1157

5. Make some Thompson MP tuning parameters visible/tunable from host (needed by NRL NEPTUNE)

6. Remove NOAHMP write statement that was making output too verbose (#321 )

## Tests Conducted:
UFS RTs on Ursa show no changes to baselines. Some testing was done at NRL with the NEPTUNE model that necessitated reversing some UFS-specific tuning commits. See https://github.com/NCAR/ccpp-physics/pull/1158

## Dependencies:
None

## Documentation:
None

## Issue (optional):
Fixes https://github.com/NCAR/ccpp-physics/issues/1155
Closes https://github.com/ufs-community/ccpp-physics/issues/320

## Contributors (optional):
@matusmartini @climbfuji @dpsarmie

### CODE REVIEW

**Review by MicroTed — APPROVED** [review]

**Review by JongilHan66 — APPROVED** [review]

File: physics/MP/Thompson/mp_thompson.F90 [hunk 1]
```diff
@@ -126,6 +133,22 @@ subroutine mp_thompson_init(ncol, nlev, con_pi, con_t0c, con_rv,     &
          lvap0 = con_hvap
          lfus = con_hfus
          
+         if (present(con_nt_c_l)) nt_c_l = con_nt_c_l
+         if (present(con_nt_c_o)) nt_c_o = con_nt_c_o
+         if (present(con_av_i)) then
```
Comment (RuiyuSun) [inline physics/MP/Thompson/mp_thompson.F90:138]: Where is this con_av_i defined, in GFS_typedefs.F90? Is it initialized as 0 ?

**Review by AnningCheng-NOAA — APPROVED** [review]
looks fine with me

File: physics/MP/Thompson/mp_thompson.F90 (hunk 1 above)
Comment (AnningCheng-NOAA) [reply physics/MP/Thompson/mp_thompson.F90:138]: Ruiyu, 
Since it is an optional, It is used only when larger than 0.  However, I think it is not used at this moment.

**Review by barlage — APPROVED** [review]

File: physics/MP/Thompson/mp_thompson.F90 (hunk 1 above)
Comment (grantfirl) [reply physics/MP/Thompson/mp_thompson.F90:138]: @RuiyuSun  It is passed in as an optional argument. It is defined in GFS_typedefs as -999 and is set by namelist, although no namelists are set up to change it. For all UFS configurations, right now, con_av_i is present, but less than 0, so the functional form is used below. For NEPTUNE, they will pass in a value > 0 and therefore, it can be used as a constant, which is what they need. A couple of commits back, I tried to just have it as an optional argument without defining it in GFS_typedefs.F90, but apparently, the CCPP framework won't allow this, hence the need to define it, but set it as a nonsense/negative value.

Comment (grantfirl) [reply physics/MP/Thompson/mp_thompson.F90:138]: @dustinswales @climbfuji Optional argument experts: is it correct to say that for variables that are optional at the scheme level at least need to be declared and have metadata in every host? For example, I originally had the `av_i` argument in this PR as an optional argument with metadata in Thompson MP, but since I knew that UFS-based hosts wouldn't need it, I didn't even add a declaration or metadata in *_typedefs. The CCPP framework errored out because it expected the host to at least have these for cross-checking. Should the framework be able to skip these variables (that are optional in the scheme but not present in the host)?

Comment (grantfirl) [reply physics/MP/Thompson/mp_thompson.F90:138]: See https://github.com/ufs-community/ccpp-physics/pull/309/commits/d85667744b6d0109360088b815b521219964eaf4 for how I originally coded it.

Comment (climbfuji) [reply physics/MP/Thompson/mp_thompson.F90:138]: That's an interesting question. I agree that the idea of "if it's an optional argument and the host doesn't know, then simply don't provide it - i.e. never present" sounds good. One question would then be if that opens the door to unintended errors. But we need to first remind ourselves what capgen does in this case. Does it create the optional variable? Or does it ignore optional variables when it generates interstitial variables in the caps? @dustinswales do you know?

**Review by mdtoyNOAA — APPROVED** [review]

File: physics/MP/Thompson/mp_thompson.F90 (hunk 1 above)
Comment (RuiyuSun) [reply physics/MP/Thompson/mp_thompson.F90:138]: Does anyone knows the answer to @climbfuji's question? @dustinswales Do you know? thanks

Comment (grantfirl) [reply physics/MP/Thompson/mp_thompson.F90:138]: In any case, I don't think that this should hold up this PR since it works as coded, although we're having to define something in the UFS that it will likely never use, which is wasteful. In this case, it's just a scalar, but one could imagine that this could be a larger issue if schemes needed large optional arrays, but in that case, we'd just make them conditionally-allocatable with a condition that always evaluates to false, so no extra memory involved, just kinda unnecessary code.

Comment (RuiyuSun) [reply physics/MP/Thompson/mp_thompson.F90:138]: OK. Thanks @grantfirl

**Review by RuiyuSun — APPROVED** [review]

**Review by rhaesung — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
Combined https://github.com/ufs-community/ccpp-physics/pull/321 into this one.

**Comment by FernandoAndrade-NOAA** [comment]
Testing for [#2882](https://github.com/ufs-community/ufs-weather-model/pull/2882) is complete, please continue with the merge process, thank you.
