### PR TITLE
Remove nine 3D arrays from CLM Lake model

### LINKED ISSUE #112: CLM Lake restarts nine 3D fields that are constant
# Description

These fields in the CLM Lake model are constant:

- lake_z3d
- lake_dz3d
- lake_soil_watsat3d
- lake_csol3d
- lake_soil_tkmg3d
- lake_soil_tkdry3d
- lake_soil_tksatu3d
- lake_clay3d
- lake_sand3d

The later seven are 2D arrays that are needlessly duplicated in the vertical (lake k) dimension. The first two are 3D. All of these are sparse arrays, zero everywhere except lake points.

All nine should be removed.

## Steps to Reproduce

1. Read the code. The lakeini in clm_lake.f90 calculates those variables. They're never modified after that.

## Additional Context

The CLM Lake Model is taking up too much disk space in the RRFS. Removing these nine variables would reduce that problem.

Problem identified by @hu5970 and @tanyasmirnova

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
There are nine 3D arrays in CLM Lake that are constant. Seven of them are 2D arrays copied to all vertical levels. All are cheap to calculate.

This PR removes all nine arrays. When the numbers are needed, they're recalculated.

To do this, I had to add a 2D array: the lakedepth before correction.

- fixes https://github.com/ufs-community/ccpp-physics/issues/112

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]

**Comment by Qingfu-Liu** [comment]
@SamuelTrahanNOAA Can you double check line 554 in file physics/clm_lake.f90?
           do c = 2,column
             z_lake(c,:) = z_lake(1,:)
             dz_lake(c,:) = z_lake(1,:)                 !line 554
           enddo

File: physics/clm_lake.f90 [hunk 1]
```diff
@@ -540,6 +547,26 @@ SUBROUTINE clm_lake_run( &
 
            lake_points = lake_points+1
 
+           call calculate_z_dz_lake(i,input_lakedepth,clm_lakedepth,z_lake(1,:),dz_lake(1,:))
+
+           do c = 2,column
+             z_lake(c,:) = z_lake(1,:)
+             dz_lake(c,:) = z_lake(1,:)
```
Comment (SamuelTrahanNOAA) [inline physics/clm_lake.f90]:
```suggestion
             dz_lake(c,:) = dz_lake(1,:)
```

**Comment by SamuelTrahanNOAA** [comment]
> Can you double check line 554 in file physics/clm_lake.f90?
> do c = 2,column
> z_lake(c,:) = z_lake(1,:)
> dz_lake(c,:) = z_lake(1,:) !line 554
> enddo

The "column" parameter is always 1, so the program never enters that loop. However, I fixed it anyway.

**Comment by Qingfu-Liu** [comment]
@Sam Trahan ***@***.***> Yes, you are right, the
column parameter c is always 1. Thanks

**Review by dustinswales — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Review by grantfirl — APPROVED** [review]
